version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - "4000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev

  crm:
    build:
      context: ./crm
    ports:
      - "3001:3000"
    volumes:
      - ./crm:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    command: npm start

  web:
    build:
      context: ./web
    ports:
      - "3002:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    command: npm start