# version: '3.8'
services:
  ecom-suite-api:
    image: ecom-suite-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecom-suite-api
    ports:
      - "4001:3000"
    volumes: 
      - ./api:/app
    env_file: 
      - ./api/.env
    networks: 
      - ecom-suite-network

  ecom-suite-web:
    image: ecom-suite-web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ecom-suite-web
    ports:
      - "4002:3000"
    volumes:
      - ./web:/app
      - ./web/node_modules:/app/node_modules
    env_file: 
      - ./web/.env
    # environment:
    #   - REACT_APP_API_URL=http://localhost:4001
    networks: 
      - ecom-suite-network

  # ecom-suite-crm:
  #   build:
  #     context: ./crm
  #   ports:
  #     - "4003:3000"
  #   volumes:
  #     - ./crm:/app
  #     # - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:4001
  #   networks: 
  #     - ecom-suite-network

networks:
  ecom-suite-network:
    driver: bridge