# version: '3.8'
services:
  ecom-suite-api:
    image: ecom-suite-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecom-suite-api
    ports:
      - "4001:3000"
    volumes: 
      - ./api:/app
      - /app/node_modules
    env_file: 
      - ./api/.env
    networks: 
      - ecom-suite-network
    depends_on:
      - ecom-suite-db

  ecom-suite-web:
    image: ecom-suite-web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ecom-suite-web
    ports:
      - "4002:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      # - ./web/node_modules:/app/node_modules
    env_file: 
      - ./web/.env
    # environment:
    #   - REACT_APP_API_URL=http://localhost:4001
    networks: 
      - ecom-suite-network

  ecom-suite-cms:
    image: ecom-suite-cms:latest
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: ecom-suite-cms
    ports:
      - "4003:3000"
    volumes:
      - ./cms:/app
      - /app/node_modules
      # - ./cms/node_modules:/app/node_modules
    env_file:
      - ./cms/.env
    networks: 
      - ecom-suite-network

  ecom-suite-db:
    image: mongo:6
    container_name: ecom-suite-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ecom-suite-db-data:/data/db
    networks:
      - ecom-suite-network

networks:
  ecom-suite-network:
    driver: bridge

volumes:
  ecom-suite-db-data: